### ISSUE TITLE
Render Dynamic Data

### ISSUE THREAD

**Issue by MattyK14** [saleel97/react-native-super-grid#1]
I'm playing with this nice module you've made and looking to implement this in the app I'm working on. I'm currently fetching the JSON objects and rendering the RN default ListView, but I'm trying to use this to do the same thing.

**Comment by saleel97** [comment]
Why is this now working? I assume you have an array of items in your state. You can pass that to the GridView. Whenever your data (and state) is updated, the GridView will be re-rendered.

If this is not working as expected, please post a sample code and I should be able to fix it quickly.

**Comment by MattyK14** [comment]
```
componentWillMount() {
    this.props.roomsFetch();
    this.createDataSource(this.props);
  }

componentWillReceiveProps(nextProps) {
    this.createDataSource(nextProps);
  }

createDataSource({ rooms }) {
    const ds = new ListView.DataSource({
      rowHasChanged: (r1, r2) => r1 !== r2
    });

    this.dataSource = ds.cloneWithRows(rooms);
  }

renderRow(room) {
   return (
     <RoomListItem room={room} />
   );
 }

<ListView
              enableEmptySections
              dataSource={this.dataSource}
              renderRow={this.renderRow}
              renderSeparator={this._renderSeparator}
            />
```

This is currently how I'm rendering my ListView

**Comment by saleel97** [comment]
Ideally, you should set `rooms` to state instead of assigning it directly to the component.

Here is how your sample can be rewritten to use super-grid (code not tested). You will have to change `itemWidth`.

```
componentWillMount() {
  this.props.roomsFetch();
  this.setState({ rooms: this.props.rooms });
}
```
```
componentWillReceiveProps(nextProps) {
  if (nextProps.rooms) {
    this.setState({ rooms: nextProps.rooms });
  }
}
```
```
<GridView
  itemWidth={130}
  items={this.state.rooms}
  renderItem={room => (<RoomListItem room={room} />)}
/>
```

**Comment by MattyK14** [comment]
It works thanks! Why would it be ideal to set rooms to state rather than leaving it at props where it's accessible?

**Comment by saleel97** [comment]
Yes, I just thought of that. As you are not modifying the rooms locally, you can set the `rooms` prop directly to the GridView.
