### ISSUE TITLE
pass index to renderItem

### ISSUE THREAD

**Issue by heaversm** [saleel97/react-native-super-grid#2]
the index from the data mapping function is useful in giving grid items different styles based on their index. 

```
<View style={rowStyle}>
        {(data || []).map((item, i) => (
          <View key={`${rowId}_${i}`} style={columnStyle}>
            <View style={itemStyle}>
              {this.props.renderItem(item,i)}
            </View>
          </View>
        ))}
      </View>
```

Since it is already accessible, suggest passing it along

**Comment by MattyK14** [comment]
@saleel 

Is there a way to get the overall index of the array of objects?
My current `renderItem` is 
```
renderItem={(room, index) =>  { return <RoomGridItem room={room} index={index} />; }}
```

But the index it returns is based on the index of that row. So with two objects per row, the indices are all 0 or 1 based on which column it is.

**Comment by saleel** [comment]
@MattyK14 This is not directly possible as data array is chunked before passing to render.

One way would be to add index info to the original data source. Something like:

```
<GridView
  itemWidth={130}
  items={[
   { i: 1, value: 'Data 1', },
   { i: 2, value: 'Data 2', }
  ]}
  renderItem={item => (<Text>{item}</Text>)}
/>
```
